<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tray_KategoriBelanja</name>
   <tag></tag>
   <elementGuidId>d283e12d-2e54-4522-ac9c-fa27c5c31235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='top-sticky']/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.category-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>507fae33-6a90-4c14-920b-80b5ed2c99b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category-search</value>
      <webElementGuid>392d1e14-7f77-49b7-8067-f8ce775af94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kategori Belanja</value>
      <webElementGuid>4e537935-a3f7-4003-ab8e-5c3306a2e6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-sticky&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-6&quot;]/div[@class=&quot;search-bar&quot;]/div[@class=&quot;category-search&quot;]</value>
      <webElementGuid>d485e956-f2fb-4876-a457-1c96142684c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='top-sticky']/div/div/div[2]/div/div</value>
      <webElementGuid>e6f6325a-04df-4c92-8647-fca7201a3ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belanja hemat bebas ongkir*'])[1]/following::div[8]</value>
      <webElementGuid>baff807b-3be0-405b-98b0-5a37d1143bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Populer'])[1]/preceding::div[1]</value>
      <webElementGuid>694a079e-eb83-44ac-9c95-22ace7d91277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div[2]/div/div</value>
      <webElementGuid>54a2fa9c-1758-449c-a9c3-67bb9b942508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Kategori Belanja' or . = ' Kategori Belanja')]</value>
      <webElementGuid>f2b80149-1bb4-4434-a94e-1eff40ce7d23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
